id: P871A1137
initial_creation_type: ocr
source_metadata:
  volumes:
    3795bc43ad50446e814bfee58e0f1d02:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: སེམས་བསྐྱེད་པ་དང་སྡོམ་པའི་ཆོ་གའི་རིམ་པ།
      total_pages: 1498
      volume_number: 65
